#!/bin/bash
arecord=""
aip=""
dom=""

#CNAME
if [[ $1 = "-t" ]] && [[ $2 = CNAME ]]; then
 	echo "Creating CNAME record"
 	arecord=$3
	aip=$4
	dom=$5
	echo 'Creatin

	DbFile=/etc/bind/db.$dom
 	echo "$arecord"'     IN         CNAME        'www" >> $DbFile

	#adjust serialnr
 	Serial=$(grep 'Serial' $DbFile)
 	SerialNumber=$(echo $Serial | sed 's/[^0-9]*//g')
	((SerialNumber++))
	newSerial='                             '"$SerialNumber"'        ;Serial'
 	sed -i "s/.*Serial.*/\t\t $newSerial/g" $DbFile

#MX record
elif [[ $1 = "-t" ]] && [[ $2 = MX ]]; then
 	echo "Creating MX record"
 	arecord=$3
 	aip=$4
	dom=$5
	echo 'Creating '"$arecord"'-record
	DBfile=/etc/bind/db.$dom
	echo '@     IN     MX     mail.nick-beauson.sb.uclllabs.be.' >> DBfile
	echo "$arecord"'     IN     A       '"$aip" >> DBfile

#A record
elif [[ $1 = "-t" ]] && [[ $2 = A ]] || [[ $1 != "-t" ]]; then
	if [[ $1 = "-t" ]]; then
 		arecord=$3
 		aip=$4
		dom=$5
	else
 		arecord=$1
		aip=$2
 		dom=$3
	fi
	echo 'Creating '"$arecord"'-record for ip: '"$aip"' & domain: '"$dom"

	DBFILE=/etc/bind/db.$dom
	echo 'file = '"$DBFILE"
	echo "$arecord"'    IN        A        '"$aip" >> $DBFILE

 	#adjust serialnr
 	Serial=$(grep 'Serial' $DBFILE)
 	SerialNumber=$(echo $Serial | sed 's/[^0-9]*//g')
 	((SerialNumber++))
	newSerial='                              '"$SerialNumber"'         ;Serial'
 	sed -i "s/.*Serial.*/\t\t $newSerial/g" $DBFILE

fi

#Restart bind9 service
echo 'Restarting bind9'
systemctl restart bind9

echo 'Finished'
