#!/bin/bash
if [[ $1 = "-t" ]] && [[ $2 = CNAME ]]; then
 	echo "Creating CNAME record"

elif [[ $1 = "-t" ]] && [[ $2 = MX ]]; then
 	echo "Creating MX record"

elif [[ $1 = "-t" ]] && [[ $2 = A ]] || [[ $1 != "-t" ]]; then
	
	arecord=""
 	aip=""
 	dom=""
	if [[ $1 = "-t" ]]; then
 		arecord=$3
 		aip=$4
		dom=$5
	else
 		arecord=$1
		aip=$2
 		dom=$3
	fi
	echo 'Creating '"$arecord"'-record for ip: '"$aip"' & domain: '"$dom"

	DBFILE=/etc/bind/db.$dom
	echo $DBFILE
	echo "$arecord"'    IN        A        '"$aip" >> DBFILE

fi
