#!/bin/bash

if  [[$(/usr/bin/id -u) -ne 0]]; then
    echo "Not running as root"
    exit
fi

zone=$1

FILENAME='db.'"$zone"'.nick-beauson.sb.uclllabs.be'
FILE=/etc/bind/$FILENAME
if test -f "$FILE"; then

	echo 'Zone '"$1"' already exists'

else

echo 'Creating zone'
#Add zone into named.conf.local
input="../bind/named.conf.local"
echo 'zone "'"$zone"'.nick-beauson.sb.uclllabs.be" { 
  type master;
  file "/etc/bind/'"$FILENAME"'";
  allow-transfer { 193.191.176.254; 193.191.177.254; 193.191.177.4; 193.191.177.160; };
};
' >> $input

#Create db.$.nick-beauson.sb.uclllabs.be file
output=/etc/bind/$FILENAME
echo 'Creating file: '"$FILENAME" 
echo '
$TTL 300     ;86400
$ORIGIN '"$zone"'.nick-beauson.sb.uclllabs.be.
@       IN      SOA    '"$zone"'.nick-beauson.sb.uclllabs.be. root.'"$zone"'.nick-beauson.sb.uclllabs.be. (
				10              ;Serial
				604800          ;Refresh
				86400           ;Retry
				2419200         ;Expire
				86400 )         ;Negative Cache TTL
;Name servers
@	IN      NS      ns.'"$zone"'.nick-beauson.sb.uclllabs.be.
@       IN      NS      ns.nick-beauson.sb.uclllabs.be.
;A records
ns      IN       A      193.191.177.210
@       IN       A      193.191.177.210
' >> $output

#update db.nick-beauson.sb.uclllabs.be
DBFILE=/etc/bind/db.nick-beauson.sb.uclllabs.be
echo "$zone"'      IN      NS      ns.nick-beauson.sb.uclllabs.be.' >> $DBFILE 

#update serial in db.nick-beauson.sb.uclllabs.be
Serial=$(grep 'Serial' ../bind/db.nick-beauson.sb.uclllabs.be)
SerialNumber=$(echo $Serial | sed 's/[^0-9]*//g')
((SerialNumber++))
newSerial='                                '"$SerialNumber"'        ;Serial'
sed -i "s/.*Serial.*/\t\t\t      $newSerial/g" ../bind/db.nick-beauson.sb.uclllabs.be

#Restart bind9 service
echo 'Restarting bind9'
systemctl restart bind9
 
echo 'Finished'
fi
