#!/bin/bash
zone=$1

FILENAME='db.'"$zone"'.nick-beauson.sb.uclllabs.be'
FILE=/etc/bind/$FILENAME
if test -f "$FILE"; then
	echo 'Zone '"$1"' already exists'
else
echo 'Creating zone'
#Add zone into named.conf.local
input="../bind/test"
echo 'zone "'"$zone"'.nick-beauson.sb.uclllabs.be" { 
  type master;
  file "/etc/bind/'"$FILENAME"'";
  allow-transfer { 193.191.176.254; 193.191.177.254; 193.191.177.4; 193.191.177.160; };
};
' >> $input

#Create db.$.nick-beauson.sb.uclllabs.be file
output=/etc/bind/$FILENAME
echo 'Creating file: '"$FILENAME" 
echo '
$TTL      86400
$ORIGIN '"$zone"'.nick-beauson.sb.uclllabs.be.
@       IN      SOA     ns.'"$zone"'.nick-beauson.sb.uclllabs.be. root.ns.'"$zone"'.nick-beauson.sb.uclllabs.be. (
				10              ;Serial
				604800          ;Refresh
				86400           ;Retry
				2419200         ;Expire
				86400 )         ;Negative Cache TTL
;Name servers
	IN      NS      ns.'"$zone"'.nick-beauson.sb.uclllabs.be.

;A records
ns      IN       A      193.191.177.210
' >> $output

echo 'Restarting bind9'
sudo service bind9 restart 

fi
